### ISSUE TITLE
I locked 10,000 STLX and dug STLG, but now my STLX is gone

### ISSUE THREAD

**Issue by espoir1989** [stlxonline/python-stlx-wallet#5]
I locked 10,000 STLX and dug STLG, but now my STLX is gone

**Comment by stlxonline** [comment]
Hi!

We are improved our staking system. Download the new wallet version here and check again: https://github.com/stlxonline/electron-gui-wallet/releases/tag/v0.0.7

**Comment by espoir1989** [comment]
Does stlx have online communication?

**Comment by stlxonline** [comment]
You can find us on discord: https://discord.gg/DyNaYcZqVV
